### ISSUE TITLE
Ability to answer medical interview

### ISSUE THREAD

**Issue by devmood** [devmood/MEDBot#7]

**Comment by wojtii** [comment]
So the meds (medical history) json should be sth like:
`
{
  "id": str,
  "id_doctor": str,
  "id_patient": str,
  "questions": [
    {"question": str, "answer": str (gathered by UI)}
  ]
}
`

**Comment by devmood** [comment]
> So the meds (medical history) json should be sth like:
> `{ "id": str, "id_doctor": str, "id_patient": str, "questions": [ {"question": str, "answer": str (gathered by UI)} ] }`

For the record sake. Now, we have:
Question(ID, question),
Answer(ID, answer),
Interview(ID, doctorID, patientID, creationTimestamp, lastActionTimestamp),
IQALink(ID, interviewID, questionID, answerID).

And all these can be easily transformed to represent mentioned structure.
